version: '3.8'

services:
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/taskdb
      - PORT=3000

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
